modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-mqtt-dc-module
name: Mqtt Device-Connector
version: v1.0.0
type: device-connector
deploymentType: single
license: "Apache License 2.0"
dependencies:
  github.com/SENERGY-Platform/mgw-cloud-proxy/mgw-module:
    version: "<v1.0.0"
    requiredServices:
      gateway:
        - refVar: GENERATOR_DEVICE_REPOSITORY_URL
          template: "http://{ref}/device-repository"
          services:
            - mgw-mqtt-dc
  github.com/SENERGY-Platform/mgw-mqtt-broker:
    version: <v2.0.0
    requiredServices:
      broker:
        - refVar: MGW_MQTT_BROKER
          template: "tcp://{ref}:1881"
          services:
            - mgw-mqtt-dc
        - refVar: MQTT_BROKER
          template: "tcp://{ref}:1881"
          services:
            - mgw-mqtt-dc
services:
  mgw-mqtt-dc:
    name: mgw-mqtt-dc
    image: ghcr.io/senergy-platform/mgw-mqtt-dc:v1.0.32
configs:
  ## broker config by dependency
  #  mqttBroker:
  #    dataType: string
  #    value: "tcp://message-broker:1881"
  #    targets:
  #      - refVar: MQTT_BROKER
  #        services:
  #          - mgw-mqtt-dc
  #    userInput:
  #      type: text
  #      name: MQTT Broker
  #      description: "e.g. tcp://message-broker:1881"
  #      group: mqtt
  ## credentials are empty
  #  mqttUsername:
  #    dataType: string
  #    optional: true
  #    targets:
  #      - refVar: MQTT_USER
  #        services:
  #          - mgw-mqtt-dc
  #    userInput:
  #      type: text
  #      name: MQTT Username
  #      group: mqtt
  #  mqttPassword:
  #    dataType: string
  #    optional: true
  #    targets:
  #      - refVar: MQTT_PW
  #        services:
  #          - mgw-mqtt-dc
  #    userInput:
  #      type: text
  #      name: MQTT Password
  #      group: mqtt
  mqttCmdClientId:
    dataType: string
    value: "mgw-mqtt-dc-cmd"
    targets:
      - refVar: MQTT_CMD_CLIENT_ID
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MQTT ClientID Event
      group: mqtt
  mqttEventClientId:
    dataType: string
    value: "mgw-mqtt-dc-event"
    targets:
      - refVar: MQTT_EVENT_CLIENT_ID
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MQTT ClientID CMD
      group: mqtt
## mgw broker config by dependency
#  mgwMqttBroker:
#    dataType: string
#    value: "tcp://message-broker:1881"
#    targets:
#      - refVar: MGW_MQTT_BROKER
#        services:
#          - mgw-mqtt-dc
#    userInput:
#      type: text
#      name: MGW MQTT Broker
#      description: "e.g. tcp://message-broker:1881"
#      group: mqtt
## mgw credentials are empty
#  mgwMqttUsername:
#    dataType: string
#    optional: true
#    targets:
#      - refVar: MGW_MQTT_USER
#        services:
#          - mgw-mqtt-dc
#    userInput:
#      type: text
#      name: MGW MQTT Username
#      group: mgw
#  mgwMqttPassword:
#    dataType: string
#    optional: true
#    targets:
#      - refVar: MGW_MQTT_PW
#        services:
#          - mgw-mqtt-dc
#    userInput:
#      type: text
#      name: MGW MQTT Password
#      group: mgw
  mgwMqttClientId:
    dataType: string
    value: "mgw-mqtt-dc"
    targets:
      - refVar: MGW_MQTT_CLIENT_ID
        services:
          - mgw-mqtt-dc
  generatorUse:
    dataType: string
    value: "true"
    targets:
      - refVar: GENERATOR_USE
        services:
          - mgw-mqtt-dc
  debug:
    dataType: string
    value: "false"
    options:
      - "true"
      - "false"
    optionsExt: false
    targets:
      - refVar: DEBUG
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: DEBUG
inputGroups: 
  mqtt:
    name: "MQTT"
  platform:
    name: "Platform"