modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-mqtt-dc-module
name: Mqtt Device-Connector
version: v0.0.2
type: device-connector
deploymentType: single
dependencies:
  github.com/SENERGY-Platform/mgw-test-module-a:
    version: <v3.0.0
    requiredServices:
      server:
        - refVar: MGW_MQTT_BROKER
          services:
            - mgw-mqtt-dc
services:
  mgw-mqtt-dc:
    name: mgw-mqtt-dc
    image: ghcr.io/senergy-platform/mgw-mqtt-dc:v1.0.0
configs:
  username:
    dataType: string
    targets:
      - refVar: GENERATOR_AUTH_USERNAME
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: Username
      group: platform
  password:
    dataType: string
    targets:
      - refVar: GENERATOR_AUTH_PASSWORD
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: Password
      group: platform
  mqttBroker:
    dataType: string
    value: "tcp://message-broker:1883"
    targets:
      - refVar: MQTT_BROKER
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MQTT Broker
      description: "e.g. tcp://message-broker:1883"
      group: mqtt
  mqttUsername:
    dataType: string
    targets:
      - refVar: MQTT_USER
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MQTT Username
      group: mqtt
  mqttPassword:
    dataType: string
    targets:
      - refVar: MQTT_PW
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MQTT Password
      group: mqtt
  mqttCmdClientId:
    dataType: string
    value: "mgw-mqtt-dc-cmd"
    targets:
      - refVar: MQTT_CMD_CLIENT_ID
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MQTT ClientID Event
      group: mqtt
  mqttEventClientId:
    dataType: string
    value: "mgw-mqtt-dc-event"
    targets:
      - refVar: MQTT_EVENT_CLIENT_ID
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MQTT ClientID CMD
      group: mqtt
  mgwMqttBroker:
    dataType: string
    value: "tcp://message-broker:1883"
    targets:
      - refVar: MGW_MQTT_BROKER
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MGW MQTT Broker
      description: "e.g. tcp://message-broker:1883"
      group: mqtt
  mgwMqttUsername:
    dataType: string
    targets:
      - refVar: MGW_MQTT_USER
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MGW MQTT Username
      group: mgw
  mgwMqttPassword:
    dataType: string
    targets:
      - refVar: MGW_MQTT_PW
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MGW MQTT Password
      group: mgw
  mgwMqttClientId:
    dataType: string
    value: "mgw-mqtt-dc"
    targets:
      - refVar: MGW_MQTT_CLIENT_ID
        services:
          - mgw-mqtt-dc
  authUrl:
    dataType: string
    value: "https://auth.senergy.infai.org"
    targets:
      - refVar: GENERATOR_AUTH_ENDPOINT
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: Auth URL
      group: platform
  permissionSearchUrl:
    dataType: string
    value: "https://api.senergy.infai.org/permissions/query"
    targets:
      - refVar: GENERATOR_PERMISSION_SEARCH_URL
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: Permission Search URL
      group: platform
  deviceRepositoryUrl:
    dataType: string
    value: "https://api.senergy.infai.org/device-repository"
    targets:
      - refVar: GENERATOR_DEVICE_REPOSITORY_URL
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: Device Repository URL
      group: platform
  generatorUse:
    dataType: bool
    value: true
    targets:
      - refVar: GENERATOR_USE
        services:
          - mgw-mqtt-dc
  debug:
    dataType: bool
    value: true
    targets:
      - refVar: DEBUG
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: DEBUG
inputGroups: 
  mqtt:
    name: "MQTT"
  mgw:
    name: "MGW"
  platfor:
    name: "Platform"