# yaml-language-server: $schema=https://raw.githubusercontent.com/SENERGY-Platform/mgw-modfile-lib/main/schema/v1.json
modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-mqtt-dc-module/bridging
name: Mqtt Device-Connector (Bridging)
version: v1.0.1
type: device-connector
deploymentType: single
license: "Apache License 2.0"
dependencies:
  github.com/SENERGY-Platform/mgw-cloud-proxy/mgw-module:
    version: "<v1.0.0"
    requiredServices:
      gateway:
        - refVar: GENERATOR_DEVICE_REPOSITORY_URL
          template: "http://{ref}/device-repository"
          services:
            - mgw-mqtt-dc
        - refVar: GENERATOR_MGW_CERT_MANAGER_URL
          template: "http://{ref}:8080/api"
          services:
            - mgw-mqtt-dc
  github.com/SENERGY-Platform/mgw-mqtt-broker:
    version: <v2.0.0
    requiredServices:
      broker:
        - refVar: MGW_MQTT_BROKER
          template: "tcp://{ref}:1881"
          services:
            - mgw-mqtt-dc
services:
  mgw-mqtt-dc:
    name: mgw-mqtt-dc
    image: ghcr.io/senergy-platform/mgw-mqtt-dc:v1.0.34
secrets:
  mqtt-credentials:
    optional: true
    type: basic-auth
    targets:
      - refVar: MQTT_USER
        item: username
        services:
          - mgw-mqtt-dc
      - refVar: MQTT_PW
        item: password
        services:
          - mgw-mqtt-dc
    userInput:
      name: MQTT Credentials
      group: remote-mqtt
configs:
  mqttBroker:
    dataType: string
    value: "tcp://message-broker:1883"
    targets:
      - refVar: MQTT_BROKER
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MQTT Broker
      description: "e.g. tcp://message-broker:1883"
      group: remote-mqtt
  mqttCmdClientId:
    dataType: string
    value: "mgw-mqtt-dc-cmd"
    targets:
      - refVar: MQTT_CMD_CLIENT_ID
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MQTT ClientID Event
      group: remote-mqtt
  mqttEventClientId:
    dataType: string
    value: "mgw-mqtt-dc-event"
    targets:
      - refVar: MQTT_EVENT_CLIENT_ID
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MQTT ClientID CMD
      group: remote-mqtt
  mqttSkipVerify:
    dataType: string
    value: "false"
    options:
      - "true"
      - "false"
    optionsExt: false
    userInput:
      name: Skip Certificate Verification
      type: text
      group: remote-mqtt
    targets:
      - refVar: MQTT_INSECURE_SKIP_VERIFY
        services:
          - mgw-mqtt-dc
## mgw broker config by dependency
#  mgwMqttBroker:
#    dataType: string
#    value: "tcp://message-broker:1883"
#    targets:
#      - refVar: MGW_MQTT_BROKER
#        services:
#          - mgw-mqtt-dc
#    userInput:
#      type: text
#      name: MGW MQTT Broker
#      description: "e.g. tcp://message-broker:1883"
#      group: mqtt
## mgw credentials are empty
#  mgwMqttUsername:
#    dataType: string
#    optional: true
#    targets:
#      - refVar: MGW_MQTT_USER
#        services:
#          - mgw-mqtt-dc
#    userInput:
#      type: text
#      name: MGW MQTT Username
#      group: mgw
#  mgwMqttPassword:
#    dataType: string
#    optional: true
#    targets:
#      - refVar: MGW_MQTT_PW
#        services:
#          - mgw-mqtt-dc
#    userInput:
#      type: text
#      name: MGW MQTT Password
#      group: mgw
  mgwMqttClientId:
    dataType: string
    value: "mgw-mqtt-dc"
    targets:
      - refVar: MGW_MQTT_CLIENT_ID
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: MGW MQTT Client ID
      group: mqtt
  generatorUse:
    dataType: string
    value: "true"
    targets:
      - refVar: GENERATOR_USE
        services:
          - mgw-mqtt-dc
  debug:
    dataType: string
    value: "false"
    options:
      - "true"
      - "false"
    optionsExt: false
    targets:
      - refVar: DEBUG
        services:
          - mgw-mqtt-dc
    userInput:
      type: text
      name: DEBUG
inputGroups: 
  mqtt:
    name: "MGW MQTT"
  remote-mqtt:
    name: "Remote MQTT"